### ISSUE TITLE
Content type error

### ISSUE THREAD

**Issue by bbaido** [dormstd/nifi-CKANProcessorBundle#4]
Hey

I'm trying to get the UploadFlowFile processor to work but I'm getting a content type error in ckan.

When the processor runs, the flowfiles get routed to success but the file doesn't get uploaded to the package in ckan. 

```[Tue Nov 05 20:20:31.008451 2019] [:error] [pid 19103] 2019-11-05 20:20:31,008 ERROR [ckanext.s3filestore.uploader] Something went very very wrong for Parameter validation failed:
[Tue Nov 05 20:20:31.008493 2019] [:error] [pid 19103] Invalid type for parameter ContentType, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
[Tue Nov 05 20:20:31.008710 2019] [:error] [pid 19103] 2019-11-05 20:20:31,008 ERROR [ckan.views.api] Parameter validation failed:
[Tue Nov 05 20:20:31.008733 2019] [:error] [pid 19103] Invalid type for parameter ContentType, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
[Tue Nov 05 20:20:31.008740 2019] [:error] [pid 19103] Traceback (most recent call last):
[Tue Nov 05 20:20:31.008753 2019] [:error] [pid 19103]   File "/usr/lib/ckan/default/src/ckan/ckan/views/api.py", line 288, in action
[Tue Nov 05 20:20:31.008767 2019] [:error] [pid 19103]     result = function(context, request_data)
[Tue Nov 05 20:20:31.008771 2019] [:error] [pid 19103]   File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
[Tue Nov 05 20:20:31.008774 2019] [:error] [pid 19103]     result = _action(context, data_dict, **kw)
[Tue Nov 05 20:20:31.008777 2019] [:error] [pid 19103]   File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 327, in resource_create
[Tue Nov 05 20:20:31.008782 2019] [:error] [pid 19103]     uploader.get_max_resource_size())
[Tue Nov 05 20:20:31.008810 2019] [:error] [pid 19103]   File "/usr/lib/ckan/default/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 289, in upload
[Tue Nov 05 20:20:31.008936 2019] [:error] [pid 19103]     self.upload_to_key(filepath, self.upload_file)
[Tue Nov 05 20:20:31.008991 2019] [:error] [pid 19103]   File "/usr/lib/ckan/default/src/ckanext-s3filestore/ckanext/s3filestore/uploader.py", line 123, in upload_to_key
[Tue Nov 05 20:20:31.009072 2019] [:error] [pid 19103]     raise e
[Tue Nov 05 20:20:31.009140 2019] [:error] [pid 19103] ParamValidationError: Parameter validation failed:
[Tue Nov 05 20:20:31.009207 2019] [:error] [pid 19103] Invalid type for parameter ContentType, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>```

Nifi Version: 1.7.1
Ckan version: 2.8.3

Do you have any idea what might be going on?
Thanks

**Comment by bbaido** [comment]
It was the s3filestore. sorry
